repos:
  - repo: local
    hooks:
      - id: run-increment-tests
        name: Run increment-version tests
        entry: bash tests/run-tests.sh --manual
        language: system
        pass_filenames: false
        files: ^(increment\.sh|tests/)